/// One row per sensor. Physical units are unspecified in the authoritative notebook.
table Sensors
	lineageTag: de5a5233-c5ee-4ce4-8c9e-25167b204da5

	/// Telemetry channel: Voltage, Rotation, Pressure or Vibration.
	column Sensor
		dataType: string
		isKey
		lineageTag: cbc4518c-a22b-4263-9074-7240b308b07e
		summarizeBy: none
		sourceColumn: Sensor

	/// Unit label carried from the source; physical units are unspecified.
	column Unit
		dataType: string
		lineageTag: 968931b2-826f-49d6-a860-aaeffdb5b769
		summarizeBy: none
		sourceColumn: Unit

	partition Sensors = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(#"Data Folder" & "/sensors.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"Sensor", type text}, {"Unit", type text}}, "en-US")
				in
				    Typed

